<?php if ($this->pageCount): ?>
<ul class="pagination">
    <?php if (isset($this->previous)): ?>
    <li class="page-item">
      <a class="page-link" href="<?= $this->url($this->route, [
                                'page' => $this->previous,
                                'action'=>'index',
                                'controller'=>'product'
                            ]); ?>" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
      <?else:?>
      <li class="page-item disabled">
      <a class="page-link" href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    <?endif?>
   
    <?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
    <li class="page-item"><a class="page-link" href="<?= $this->url($this->route, [
                                    'page' => $page,
                                    'action'=>'index',
                                    'controller'=>'product'
                                ]); ?>"> <?= $page; ?></a>
    </li>
    <? else: ?>
    <li class="page-item active"><a class="page-link" href="#"><?= $page; ?></a></li>
    <? endif?>
    <?endforeach?>
    <?php if (isset($this->next)): ?>
    <li class="page-item">
      <a class="page-link" href="<?= $this->url($this->route, [
                                'page' => $this->next,
                                'action'=>'index',
                                'controller'=>'product'
                            ]); ?>" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
      <? else:?>
      <li class="page-item disabled">
      <a class="page-link" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    <? endif?>
</ul>

<?php endif ?>