<?php
$form->setAttributes([
    'class'=>'form-horizontal',
    'action'=>$this->url('login',[
        'controller'=> 'auth',
        'action'=>'login'
    ]),
    'method'=>'POST'
]);
$password = $form->get('password');
$email = $form->get('email');
$btn = $form->get('btnSubmit');
$form->prepare();
?>
<div class="row">
    <div class="col-sm-6 col-sm-offset-3" >
        <h2 class="text-center">Login </b></h2>
        <br>
        <div class="row">
            <div class="col-sm-12 my-message">
                <?= $this->flashMessenger()->render('error',['alert','alert-danger']);?>
            </div>
        </div>
        <?=$this->form()->openTag($form)?>
        
        <div class="form-group">
            <?=$this->formLabel($email)?>
            <div class="col-sm-8">
                <?php
                echo $this->formElement($email);
                echo $this->formElementErrors($email);
                ?>
            </div>
        </div>
        <div class="form-group">
            <?=$this->formLabel($password)?>
            <div class="col-sm-8">
                <?php
                echo $this->formElement($password);
                echo $this->formElementErrors($password);
                ?>
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-6">
                <?= $this->formElement($btn);?>
            </div>
            <div class="col-sm-offset-4 col-sm-6">
                <a href="user/forget-password">Quên mật khẩu</a>
            </div>

        </div>

        <?=$this->form()->closeTag()?>
    </div>
</div>