<?php
$form = $this->form;
$form->setAttributes([
    'class'=>'form-horizontal',
    'action'=>$this->url('user',[
        'controller'=> 'user',
        'action'=>'forgetPassword',
    ])
]);
$email = $form->get('email');
$btn = $form->get('btnSubmit');
$form->prepare();

?>
<div class="row">
    <div class="col-sm-6 col-sm-offset-3" >
        <h2 class="text-center">Quên mật khẩu</h2>
        <br>
        <div class="row">
            <div class="col-sm-12 my-message">
                <?= $this->flashMessenger()->render('error',['alert','alert-danger']);?>
                <?= $this->flashMessenger()->render('success',['alert','alert-success']);?>
            </div>
        </div>
        <?=$this->form()->openTag($form)?>
        
        <div class="form-group">
            <?=$this->formLabel($email)?>
            <div class="col-sm-8">
                <?php
                echo $this->formElement($email);
                echo $this->formElementErrors($email);
                ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-6">
                <?= $this->formElement($btn);?>
            </div>
        </div>

        <?=$this->form()->closeTag()?>
    </div>
</div>