<?php

$form->setAttributes([
    'class'=>'form-horizontal',
    'action'=>$this->url('user',[
        'controller'=> 'user',
        'action'=>'setPassword',
        'token'=>$token
    ]),
    'method'=>'POST'
]);

$password = $form->get('password');
$confirmPw = $form->get('confirm_password');
$btn = $form->get('btnSubmit');
$form->prepare();

?>
<div class="row">
    <div class="col-sm-6 col-sm-offset-3" >
        <h2 class="text-center">Đổi mật khẩu </b></h2>
        <br>
        <div class="row">
            <div class="col-sm-12 my-message">
                <?= $this->flashMessenger()->render('error',['alert','alert-danger']);?>
            </div>
        </div>
        <?=$this->form()->openTag($form)?>
        <input type="hidden" name='token' value="<?=$token?>">
        
        <div class="form-group">
            <?=$this->formLabel($password)?>
            <div class="col-sm-8">
                <?php
                echo $this->formElement($password);
                echo $this->formElementErrors($password);
                ?>
            </div>
        </div>
        
        <div class="form-group">
            <?=$this->formLabel($confirmPw)?>
            <div class="col-sm-8">
                <?php
                echo $this->formElement($confirmPw);
                echo $this->formElementErrors($confirmPw);
                ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-6">
                <?= $this->formElement($btn);?>
            </div>
        </div>

        <?=$this->form()->closeTag()?>
    </div>
</div>