<?php

	$form = $this->form;
	$file = $form->get('file-upload');
	$button = $form->get('btnSubmit');

	$form->setAttributes([
		'enctype'=>'multipart/form-data',
		'action'=>'#'
		
	]);
?>
<style>
	.text-danger{margin-top: 10px}
</style>
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<h3>Upload file</h3>
		<?= $this->form()->openTag($form)?>
			<div class="form-group">
				<?= $this->formLabel($file)?>
				<?= $this->formElement($file)?>
				<?= $this->formElementErrors($file)?>
			</div>
			<div class="form-group">
				<?= $this->formRow($button)?>
			</div>
		<?= $this->form()->closeTag()?>
	</div>
</div>