<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title></title>
</head>
<body>
	<table>
		<thead>
			<th>idbv</th>
			<th>Tiêu đề</th>
			<th>Tóm tắt</th>
			<th>Ngày</th>
			<th>idLoai</th>
			<th>urlHinh</th>
		</thead>
		<tbody>
			<?php
				foreach($result as $p):
				$p = (object)$p;
			?>
			<tr>
				<td><?php $p->idbv?></td>
				<td><?php $p->TieuDe?></td>
				<td><?php $p->TomTat?></td>
				<td><?php $p->Ngay?></td>
				<td><?php $p->idLoai?></td>
				<td><?php $p->urlHinh?></td>
			</tr>
			
			<?php
				endforeach;
			?>
		</tbody>
	</table>
</body>
</html>